server:
  port: 8300

spring:
  web:
    resources:
      add-mappings: false
  profiles:
    active: local # 기본 실행 프로파일
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    net.ttddyy.dsproxy.listener: DEBUG
    com.github.gavlyukovskiy.boot.jdbc.decorator: DEBUG


jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiry: ${JWT_EXPIRATION_TIME}
  refresh-token-expiry: ${JWT_REFRESH_EXPIRATION_TIME}
  skip-urls:
    - /no-auth/**
    - /swagger-ui/**
    - /v3/api-docs/**

oauth2:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect_uri: ${GOOGLE_REDIRECT_URI}
    grant_type: "authorization_code"
  github:
    client-id: ${GITHUB_CLIENT_ID}
    client-secret: ${GITHUB_CLIENT_SECRET}
    redirect_uri: ${GITHUB_REDIRECT_URI}
    grant_type: "authorization_code"

resilience4j:
  circuitbreaker:
    instances:
      googleOAuth:
        slidingWindowSize: 10               # 최근 10개의 호출 기준
        minimumNumberOfCalls: 5             # 최소 5번 호출돼야 판단
        failureRateThreshold: 50            # 실패율 50% 이상이면 OPEN
        waitDurationInOpenState: 10s        # 10초 후 HALF_OPEN으로 전환
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true
      githubOAuth:
        slidingWindowSize: 10               # 최근 10개의 호출 기준
        minimumNumberOfCalls: 5             # 최소 5번 호출돼야 판단
        failureRateThreshold: 50            # 실패율 50% 이상이면 OPEN
        waitDurationInOpenState: 10s        # 10초 후 HALF_OPEN으로 전환
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true
  retry:
    instances:
      googleOAuth:
        maxAttempts: 3        # 총 3번 시도 (최초 + 2회)
        waitDuration: 500ms   # 각 재시도 간 지연
        retryExceptions:
          - com.reservation.support.exception.BusinessException
      githubOAuth:
        maxAttempts: 3        # 총 3번 시도 (최초 + 2회)
        waitDuration: 500ms   # 각 재시도 간 지연
        retryExceptions:
          - com.reservation.support.exception.BusinessException
