spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  profiles:
    active: local # 기본 실행 프로파일
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiry: ${JWT_EXPIRATION_TIME}
  refresh-token-expiry: ${JWT_REFRESH_EXPIRATION_TIME}
  skip-urls:
    - /no-auth/**
    - /swagger-ui/**
    - /v3/api-docs/**

oauth2:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect_uri: ${GOOGLE_REDIRECT_URI}
    grant_type: "authorization_code"
  github:
    client-id: ${GITHUB_CLIENT_ID}
    client-secret: ${GITHUB_CLIENT_SECRET}
    redirect_uri: ${GITHUB_REDIRECT_URI}
    grant_type: "authorization_code"

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
